version: 2.0
jobs:
  "blog":
    docker:
    - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/jhipster-microservices/blog
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout:
        path: ~/jhipster-microservices
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn integration-test
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test

  "store":
    docker:
    - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/jhipster-microservices/store
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout:
        path: ~/jhipster-microservices
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn integration-test
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test

workflows:
  version: 2
  build:
    jobs:
    - "blog"
    - "store"